# Use the official Neo4j image
FROM neo4j:4.4.28

# Set environment variables for Neo4j
# Use the default username 'neo4j' and set a password of at least 8 characters
ENV NEO4J_AUTH=neo4j/neo4jtest

# Expose the ports Neo4j uses
EXPOSE 7474 7687

# The default command to run when starting the container
CMD ["neo4j"]
